version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "8080:8080"
    networks:
      - webnet
    cpus: 0.25        # Limit to 0.5 CPU cores
    mem_limit: 128m    # Limit to 256 MB RAM

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    ports:
      - "8081:8081"
    networks:
      - webnet
    cpus: 0.25
    mem_limit: 128m

networks:
  webnet:
    driver: bridge
