FROM python:3.13-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./flask/flask_app.py /code/

COPY ./flask/wsgi.py /code/

CMD ["gunicorn", "-w", "8", "-b", "0.0.0.0:8080", "wsgi:app"]