FROM python:3.13-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./flask_async/flask_async_app.py /code/

CMD ["hypercorn", "flask_async_app:app", "--bind", "0.0.0.0:8082", "--workers", "4"]