version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "8080:8080"
    networks:
      - webnet

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    ports:
      - "8081:8081"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
